kind: template
load: merged.yaml
data:
  service: wiki
  AWS_REGION: eu-west-1
  LOG_LEVEL: info
  ASYNC_CONTEXT: 1
  env_var_from_secret:
    REGISTRY_PASSWORD: REGISTRY_PASSWORD
    GITHUB_TOKEN: git_pat
    DRONE_TOKEN: DRONE_TOKEN
    SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    ALLOW_PUSH_DEPLOYMENT: ALLOW_PUSH_DEPLOYMENT
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
    SONAR_TOKEN: SONAR_TOKEN
  dev:
    values:
      deployment.secret: arn:aws:secretsmanager:eu-west-1:221581667315:secret:/wiki/dev-Pgb1Q5
      ingress.hostname: wiki.deel.training
      deployment.env.INGRESS: wiki.deel.training
