image: gitpod/workspace-postgres

tasks:
  - name: Yarn Server - legacy:build
    init: >
      cp config.sample.yml config.yml &&
      nvm install v18.13 &&
      yarn install &&
      yarn legacy:build &&
      gp sync-done build-legacy &&
      gp sync-await build
    command:  yarn dev
    openMode: split-left

  - name: Yarn UX - build
    init: >
      gp sync-await build-legacy &&
      cd ux &&
      yarn install &&
      yarn build &&
      gp sync-done build
    command: yarn dev
    openMode: split-right

ports:
  - name: Web App
    port: 3000
    description: The main application web server. Use the login admin@example.com / 12345678 to login.
    visibility: private
    onOpen: open-browser
  - name: UX dev
    port: 3001
    visibility: private
    onOpen: ignore
  - name: pgAdmin
    description: a PostgreSQL administration tool. Use the login dev / 123123 to login.
    port: 8000
    visibility: private
    onOpen: ignore
  - name: postgresql Server
    port: 5432
    onOpen: ignore

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - christian-kohler.path-intellisense
    - octref.vetur
