{{- if .Values.extraEnv }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "wiki.fullname" $ }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "wiki.name" $ }}
    helm.sh/chart: {{ template "wiki.chart" $ }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
  {{- toYaml .Values.extraEnv | nindent 2 }}
{{- end }}
