apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wiki.fullname" $ }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "wiki.name" $ }}
    helm.sh/chart: {{ template "wiki.chart" $ }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "wiki.name" $ }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "wiki.name" $ }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret | quote }}
      {{- end }}
      volumes:
        - name: wiki-secret-config
          secret:
            defaultMode: 0644
            secretName: {{ template "wiki.fullname" $ }}-config
      containers:
        - name: wiki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc"
            - name: DB_PORT
              value: {{ .Values.postgresql.service.port | quote }}
            - name: DB_USER
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgresql"
                  key: postgresql-password
            - name: DB_NAME
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
          {{- if .Values.extraEnv }}
          envFrom:
            - configMapRef:
                name: {{ template "wiki.fullname" $ }}
          {{- end }}
          volumeMounts:
            - mountPath: /wiki/config.yml
              name: wiki-secret-config
              readOnly: true
              subPath: config.yml
          {{- with default .Values.resources .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with default .Values.nodeSelector .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.affinity .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with default .Values.tolerations .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
