apiVersion: v1
kind: Service
metadata:
  name: {{ template "wiki.fullname" $ }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ template "wiki.name" $ }}
    helm.sh/chart: {{ template "wiki.chart" $ }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ default .Values.service.type "ClusterIP" }}
  ports:
  - port: {{ default .Values.service.port 80 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ template "wiki.name" $ }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
