apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "playbook.fullname" . }}-volume
  labels:
    chart: playbook-0.2.0
    app: {{ template "playbook.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs