port: 3000
bindIP: 0.0.0.0
db:
  type: postgres
  host: db
  port: 5432
  user: wikijs
  pass: alksjlfwiersalkdflkaj
  db: wiki
logLevel: info
ssl:
  enabled: true
  port: 3443
  provider: letsencrypt
  domain: wiki.learntibetanlanguage.org
  subscriberEmail: andrewcarterhughes@gmail.com

