apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{$.Values.deployment.name}}
  labels:
    app: {{$.Values.deployment.name}}
spec:
  ingressClassName: nginx
  rules:
    - host: {{$.Values.ingress | quote}}
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: {{$.Values.deployment.name}}
                port:
                  number: 80
