apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.deployment.name}}
  labels:
    app: {{$.Values.deployment.name}}
spec:
  selector:
    app: {{$.Values.deployment.name}}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
